language: python

python:
    - "3.7"
env:
    - SECRET_KEY='TEST'
services:
   - postgresql
install:
    - pipenv install

script:
    - python manage.py test


# script:
#     -  coverage run --source='authentication' manage.py test && coverage report && coverage html
# after_success:
#     - codecov